name: Build COSMIC components
on: workflow_dispatch

permissions: {}

# Prevents concurrent runs of the workflow
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.component }}
    env:
      VERSION: 1.4.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - cosmic-applets
          - cosmic-app-library
          - cosmic-bg
          - cosmic-comp
          - cosmic-greeter
          - cosmic-icons
          - cosmic-idle
          - cosmic-initial-setup
          - cosmic-launcher
          - cosmic-monitor
          - cosmic-notifications
          - cosmic-osd
          - cosmic-panel
          - cosmic-randr
          - cosmic-screenshot
          - cosmic-session
          - cosmic-settings
          - cosmic-settings-daemon
          - cosmic-workspaces
          - pop-launcher
          - xdg-desktop-portal-cosmic
        arch:
          - amd64
        include:
          - {component: cosmic-wallpapers, arch: all}

    steps:
      - name: Checkout sources
        if: ${{ matrix.component != 'cosmic-workspaces' && matrix.component != 'pop-launcher' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/${{ matrix.component }}'
          ref: 'epoch-${{ env.VERSION }}'
          persist-credentials: false

      # Special case for cosmic-workspaces repository (repo = pop-os/cosmic-workspaces-epoch)
      - name: Checkout sources for cosmic-workspaces
        if: ${{ matrix.component == 'cosmic-workspaces' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/cosmic-workspaces-epoch'
          ref: 'epoch-${{ env.VERSION }}'
          persist-credentials: false

      # Special case for pop-launcher repository (repo = pop-os/launcher)
      - name: Checkout sources for pop-launcher
        if: ${{ matrix.component == 'pop-launcher' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/launcher'
          ref: 'epoch-${{ env.VERSION }}'
          persist-credentials: false

      - name: Checkout changelog for ${{ matrix.component }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          path: local-debian
          sparse-checkout: |
            changelog/${{ matrix.component }}
          sparse-checkout-cone-mode: false
          persist-credentials: false

      - name: Check changelog for ${{ matrix.component }}
        run: |
          filename="local-debian/changelog/${{ matrix.component }}"
          if [ -r "$filename" ]; then
            cp -v "$filename" debian/changelog
            echo "### changelog file"
            cat debian/changelog
          else
            echo "ERROR: no changelog file for ${{ matrix.component }}"
            exit 1
          fi

      - name: Build package
        uses: jtdor/build-deb-action@473136f14a42a231124c1f7cefaedfe941203c38  #v1.9.1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          extra-build-deps: devscripts dpkg-dev  # needed for dch and dpkg-parsechangelog tools
          setup-hook: |
            # TODO: merge in 'before-build-hook'
            # Replace build target in debian/rules files + no vendoring
            sed -i 's/VENDOR ?= 1/VENDOR ?= 0/' debian/rules
            sed -i 's/build-vendored/build-release/' debian/rules
            echo "### debian/rules file"
            cat debian/rules

            # Special case for cosmic-osd => rewrite debian/control file to remove
            # unecessary Build-Depends on cosmic-randr
            if grep -q "cosmic-osd" Cargo.toml; then
              sed -i '/cosmic-randr,/d' debian/control
            fi
          before-build-hook: |
            # Special case for cosmic-initial-setup, cosmic-osd, cosmic-settings
            # and cosmic-session => rewrite debian/rules file to remove vendor
            if grep "name" Cargo.toml | grep -q -E "cosmic-initial-setup|cosmic-osd|cosmic-session"; then
              sed -i '/override_dh_auto_clean/,+2d' debian/rules
            fi
            if [ "${{ matrix.component }}" = "cosmic-settings" ]]; then
              sed -i '/override_dh_auto_clean/,+2d' debian/rules
            fi
            echo "### debian/rules file"
            cat debian/rules

            # TODO: Commit debian/changelog after release to keep changes
            echo "::group::Update changelog"
            if [ "$(dpkg-parsechangelog --show-field Version)" != "${{ env.VERSION }}" ]; then
              DEBEMAIL=foxy@free.fr DEBFULLNAME="Laurent Cheylus" dch -v ${{ env.VERSION }}  --distribution testing "new version for upstream release COSMIC epoch-${{ env.VERSION }}"
            fi
            cat debian/changelog
            echo "::endgroup::"

          buildpackage-opts: --build=binary --no-sign

      - name: Get infos/contents for package
        run: |
          if [ "${{ matrix.component }}" == "cosmic-greeter" ]; then
            echo "::group::Get infos for ${{ matrix.component }} package"
            dpkg --info debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }} package"
            dpkg --contents debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get infos for ${{ matrix.component }}-daemon package"
            dpkg --info debian/artifacts/${{ matrix.component }}-daemon_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }}-daemon package"
            dpkg --contents debian/artifacts/${{ matrix.component }}-daemon_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
          else
            echo "::group::Get infos for ${{ matrix.component }} package"
            dpkg --info debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }} package"
            dpkg --contents debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
          fi

      - name: Upload package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
          if-no-files-found: error
          retention-days: 1
          archive: false

          # Special case for cosmic-greeter component: 2 packages built
      - name: Upload cosmic-greeter-daemon
        if: ${{ matrix.component == 'cosmic-greeter' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.component }}-daemon_${{ env.VERSION }}_${{ matrix.arch }}.deb
          if-no-files-found: error
          retention-days: 1
          archive: false
