name: Build COSMIC apps
on: workflow_dispatch

permissions: {}

# Prevents concurrent runs of the workflow
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-apps:
    name: Build ${{ matrix.app }}
    env:
      VERSION: 1.5.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [cosmic-edit, cosmic-files, cosmic-monitor, cosmic-player, cosmic-store, cosmic-term]

    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/${{ matrix.app }}'
          ref: 'epoch-${{ env.VERSION }}'
          persist-credentials: false

      - name: Build package
        uses: jtdor/build-deb-action@473136f14a42a231124c1f7cefaedfe941203c38  #v1.9.1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: ca-certificates
          before-build-hook: |
            # Replace build target in debian/rules files + no vendoring
            sed -i 's/VENDOR ?= 1/VENDOR ?= 0/' debian/rules
            sed -i 's/build-vendored/build-release/' debian/rules
            echo "### debian/rules file"
            cat debian/rules

            # Remove .cargo/config.toml with vendored sources
            if [ -f .cargo/config.toml ]; then rm .cargo/config.toml; fi

      - name: Get infos/contents for package
        run: |
          echo "::group::Get infos for ${{ matrix.app }} package"
          dpkg --info debian/artifacts/${{ matrix.app }}_${{ env.VERSION }}_amd64.deb
          echo "::endgroup::"
          echo "::group::Get contents for ${{ matrix.app }} package"
          dpkg --contents debian/artifacts/${{ matrix.app }}_${{ env.VERSION }}_amd64.deb
          echo "::endgroup::"

      - name: Upload package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.app }}_${{ env.VERSION }}_amd64.deb
          if-no-files-found: error
          retention-days: 1
          archive: false
