name: Build packages for pop-sound-theme
on: workflow_dispatch

jobs:
  cosmic-build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {name: pop-sound-theme, repo: gtk-theme, version: 5.5.1, arch: all }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          repository: 'pop-os/${{ matrix.repo }}'

      - name: Build package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          extra-build-deps: devscripts
          buildpackage-opts: --build=binary --no-sign

      - name: Get infos/contents for packages
        run: |
          echo "::group::Get infos for ${{ matrix.name }} package"
          dpkg --info debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_${{ matrix.arch }}.deb
          echo "::endgroup::"
          echo "::group::Get contents for ${{ matrix.name }} package"
          dpkg --contents debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_${{ matrix.arch }}.deb
          echo "::endgroup::"

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          path: debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_${{ matrix.arch }}.deb
          if-no-files-found: error
          retention-days: 1
          archive: false
