name: Build package cosmic-term
on: workflow_dispatch

jobs:
  cosmic-term:
    env:
      NAME: cosmic-term
      VERSION: 1.4.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          repository: 'pop-os/${{ env.NAME }}'
          ref: 'epoch-${{ env.VERSION }}'

      - name: Build package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          buildpackage-opts: --build=binary --no-sign
          setup-hook: |
            # Replace build target in debian/rules files + no vendoring
            sed -i 's/VENDOR ?= 1/VENDOR ?= 0/' debian/rules
            sed -i 's/build-vendored/build-release/' debian/rules
            echo "### debian/rules file"
            cat debian/rules

            # Remove .cargo/config.toml with vendored sources
            if [ -f .cargo/config.toml ]; then rm .cargo/config.toml; fi

      - name: Get infos/contents for package
        run: |
          echo "::group::Get infos"
          dpkg --info debian/artifacts/${{ env.NAME }}_${{ env.VERSION }}_amd64.deb
          echo "::endgroup::"
          echo "::group::Get contents"
          dpkg --contents debian/artifacts/${{ env.NAME }}_${{ env.VERSION }}_amd64.deb
          echo "::endgroup::"
      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          path: debian/artifacts/${{ env.NAME }}_${{ env.VERSION }}_amd64.deb
          if-no-files-found: error
          retention-days: 1
          archive: false
