# Workflow to build Debian package cosmic-randr
name: Build package cosmic-randr
on: workflow_dispatch

jobs:
  cosmic-randr:
    env:
      NAME: cosmic-randr
      VERSION: 1.4.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          repository: 'pop-os/${{ env.NAME }}'
          ref: 'epoch-${{ env.VERSION }}'

      - name: Build package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          extra-build-deps: lsb-release devscripts
          # TODO Copy debian/changelog from repository (commit after local modifications with dch)
          before-build-hook: |
            DEBEMAIL=foxy@free.fr DEBFULLNAME="Laurent Cheylus" dch -v ${{ env.VERSION }}  "Release for COSMIC epoch-${{ env.VERSION }}"
            echo "::group::lsb_release -a"
            lsb_release -a
            echo "::endgroup::"
            echo "::group::uname -a"
            uname -a
            echo "::endgroup::"
          buildpackage-opts: --build=binary --no-sign

      - name: Get infos/contents for package
        run: |
          echo "::group::Get infos"
          dpkg --info debian/artifacts/${{ env.NAME }}_${{ env.VERSION }}_amd64.deb
          echo "::endgroup::"
          echo "::group::Get contents"
          dpkg --contents debian/artifacts/${{ env.NAME }}_${{ env.VERSION }}_amd64.deb
          echo "::endgroup::"

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          path: debian/artifacts/${{ env.NAME }}_${{ env.VERSION }}_amd64.deb
          if-no-files-found: error
          retention-days: 1
          archive: false
