name: Build packages for COSMIC components
on: workflow_dispatch

jobs:
  cosmic-build:
    name: Build ${{ matrix.component }}
    env:
      VERSION: 1.4.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - cosmic-applets
          - cosmic-app-library
          - cosmic-bg
          - cosmic-comp
          - cosmic-greeter
          - cosmic-icons
          - cosmic-idle
          - cosmic-initial-setup
          - cosmic-launcher
          - cosmic-monitor
          - cosmic-notifications
          - cosmic-osd
          - cosmic-panel
          - cosmic-randr
          - cosmic-screenshot
          - cosmic-session
          - cosmic-settings
          - cosmic-settings-daemon
          - cosmic-workspaces
          - pop-launcher
          - xdg-desktop-portal-cosmic
        arch:
          - amd64
        include:
          - {component: cosmic-wallpapers, arch: all}

    steps:
      - name: Checkout sources
        if: ${{ matrix.component != 'cosmic-workspaces' && matrix.component != 'pop-launcher' }}
        uses: actions/checkout@v7
        with:
          repository: 'pop-os/${{ matrix.component }}'
          ref: 'epoch-${{ env.VERSION }}'

      # Special case for cosmic-workspaces repository (repo = pop-os/cosmic-workspaces-epoch)
      - name: Checkout sources for cosmic-workspaces
        if: ${{ matrix.component == 'cosmic-workspaces' }}
        uses: actions/checkout@v7
        with:
          repository: 'pop-os/cosmic-workspaces-epoch'
          ref: 'epoch-${{ env.VERSION }}'

      # Special case for pop-launcher repository (repo = pop-os/launcher)
      - name: Checkout sources for pop-launcher
        if: ${{ matrix.component == 'pop-launcher' }}
        uses: actions/checkout@v7
        with:
          repository: 'pop-os/launcher'
          ref: 'epoch-${{ env.VERSION }}'

      - name: Build package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          extra-build-deps: devscripts
          setup-hook: |
            # Replace build target in debian/rules files + no vendoring
            sed -i 's/VENDOR ?= 1/VENDOR ?= 0/' debian/rules && sed -i 's/build-vendored/build-release/' debian/rules && cat debian/rules
            # Special case for cosmic-osd => rewrite debian/control file to remove
            # unecessary Build-Depends on cosmic-randr
            if grep -q "cosmic-osd" Cargo.toml; then
              sed -i '/cosmic-randr,/d' debian/control
            fi
          before-build-hook: |
            # Special case for cosmic-initial-setup a and cosmic-session
            # => rewrite debian/rules file to remove vendor
            if grep -q "cosmic-initial-setup" Cargo.toml; then
              sed -i '/override_dh_auto_clean/,+2d' debian/rules
            fi
            if grep -q "cosmic-session" Cargo.toml; then
              sed -i '/override_dh_auto_clean/,+2d' debian/rules
            fi
            # TODO
            # - Copy debian/changelog from repository
            # - Commit debian/changelog after release to keep changes
            # - Do not update changelog if not needed
            #
            DEBEMAIL=foxy@free.fr DEBFULLNAME="Laurent Cheylus" dch -v ${{ env.VERSION }}  "Release for COSMIC epoch-${{ env.VERSION }}"

          buildpackage-opts: --build=binary --no-sign

      - name: Get infos/contents for package
        run: |
          if [ "${{ matrix.component }}" == "cosmic-greeter" ]; then
            echo "::group::Get infos for ${{ matrix.component }} package"
            dpkg --info debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }} package"
            dpkg --contents debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get infos for ${{ matrix.component }}-daemon package"
            dpkg --info debian/artifacts/${{ matrix.component }}-daemon_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }}-daemon package"
            dpkg --contents debian/artifacts/${{ matrix.component }}-daemon_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
          else
            echo "::group::Get infos for ${{ matrix.component }} package"
            dpkg --info debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }} package"
            dpkg --contents debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
            echo "::endgroup::"
          fi

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          path: debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
          if-no-files-found: error
          retention-days: 1
          archive: false

          # Special case for cosmic-greeter component: 2 packages built
      - name: Upload cosmic-greeter-daemon
        if: ${{ matrix.component == 'cosmic-greeter' }}
        uses: actions/upload-artifact@v7
        with:
          path: debian/artifacts/${{ matrix.component }}-daemon_${{ env.VERSION }}_${{ matrix.arch }}.deb
          if-no-files-found: error
          retention-days: 1
          archive: false
