name: Test workflow to update changelog
on: workflow_dispatch

jobs:
  update-changelog:
    name: Update changelog for ${{ matrix.component }}
    permissions:  # Allow to commit file
      contents: write
    env:
      VERSION: 1.4.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - cosmic-bg
          - cosmic-icons
          - cosmic-launcher
          - cosmic-panel
          - cosmic-randr
          - cosmic-workspaces
          - pop-launcher

    steps:
      - name: Checkout sources for ${{ matrix.component }}
        if: ${{ matrix.component != 'cosmic-workspaces' && matrix.component != 'pop-launcher' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/${{ matrix.component }}'
          ref: 'epoch-${{ env.VERSION }}'
          persist-credentials: false

      # Special case for cosmic-workspaces repository (repo = pop-os/cosmic-workspaces-epoch)
      - name: Checkout sources for cosmic-workspaces
        if: ${{ matrix.component == 'cosmic-workspaces' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/cosmic-workspaces-epoch'
          ref: 'epoch-${{ env.VERSION }}'
          persist-credentials: false

      # Special case for pop-launcher repository (repo = pop-os/launcher)
      - name: Checkout sources for pop-launcher
        if: ${{ matrix.component == 'pop-launcher' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/launcher'
          ref: 'epoch-${{ env.VERSION }}'
          persist-credentials: false

      - name: Checkout changelog for ${{ matrix.component }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          sparse-checkout: |
            changelog
          path: local-repo

      - name: Check checkouts
        run: |
          pwd
          ls -l
          if [ -d "local-repo" ]; then
            ls -R local-repo
          fi
          filename="local-repo/changelog/${{ matrix.component }}"
          if [ -r "$filename" ]; then
            echo "### changelog file"
            cat "$filename"
          else
            echo "ERROR: no changelog file for ${{ matrix.component }}"
            exit 1
          fi
          echo "### check Git remote"
          cd local-repo
          git remote -v

      - name: Update changelog for ${{ matrix.component }}
        run: |
          sudo apt install -y devscripts
          cp "local-repo/changelog/${{ matrix.component }}" debian/changelog
          DEBEMAIL=foxy@free.fr DEBFULLNAME="Laurent Cheylus" dch -v ${{ env.VERSION }}  --distribution testing "new version for upstream release COSMIC epoch-${{ env.VERSION }}"
          cat debian/changelog

      - name: Commit changelog for ${{ matrix.component }}
        run: |
          cp debian/changelog "local-repo/changelog/${{ matrix.component }}"
          cd local-repo

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "changelog/${{ matrix.component }}"
          git commit -m "Update changelog for ${{ matrix.component }} - version ${{ env.VERSION }}"
          git push
