name: Test workflow to update changelog
on: workflow_dispatch

jobs:
  update-changelog:
    name: Update changelog for ${{ matrix.component }}
    permissions:  # Allow to commit file
      contents: write
    env:
      VERSION: 1.4.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - cosmic-bg
          - cosmic-icons
          - cosmic-launcher
          - cosmic-panel
          - cosmic-randr
          - cosmic-workspaces
          - pop-launcher

    steps:
      - name: Checkout changelog for ${{ matrix.component }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          sparse-checkout: |
            changelog/${{ matrix.component }}
          sparse-checkout-cone-mode: false

      - name: Check checkouts
        run: |
          ls -l changelog
          filename="changelog/${{ matrix.component }}"
          if [ -r "$filename" ]; then
            echo "### changelog file"
            mkdir debian
            cp -v "$filename" debian/changelog
            cat debian/changelog
          else
            echo "ERROR: no changelog file for ${{ matrix.component }}"
            exit 1
          fi

      - name: Update changelog for ${{ matrix.component }}
        run: |
          sudo apt install -y devscripts
          DEBEMAIL=foxy@free.fr DEBFULLNAME="Laurent Cheylus" dch -v ${{ env.VERSION }}  --distribution testing "new version for upstream release COSMIC epoch-${{ env.VERSION }}"
          cat debian/changelog
          cp -v debian/changelog "changelog/${{ matrix.component }}"

      - name: Upload changelog file for ${{ matrix.component }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          name: ${{ matrix.component }}
          path: "changelog/${{ matrix.component }}"
          if-no-files-found: error
          retention-days: 1

  commit-changelog:
    name: Commit updated changelog
    needs: update-changelog
    runs-on: ubuntu-latest
    permissions:  # Allow to commit file
      contents: write

    steps:
      - name: Download changelog files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  #v8.0.1

      - name: Check changelog files
        run: ls -l changelog

      - name: Commit changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "changelog"
          git commit -m "Update changelog for COSMIC components - version ${{ env.VERSION }}"
          git push
