name: Create dynamic badge
on: workflow_dispatch

permissions: {}

# Prevents concurrent runs of the workflow
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-badge:
    name: Create badge
    runs-on: ubuntu-latest

    steps:
      - uses: schneegans/dynamic-badges-action@28b0fa8bdeb46170ac397105ece0c1fe58f68910  #v1.9.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6709cbe37e469a749fd3e179dd03c0db
          filename: cosmic-badge.json
          forceUpdate: true
          label: COSMIC version
          message: Epoch 1.5.0
          color: orange
