# Workflow to build Debian package pop-icon-theme
name: Build package pop-icon-theme
on: workflow_dispatch

jobs:
  pop-icon-theme:
    env:
      VERSION: 3.5.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: 'pop-os/icon-theme'
          ref: 'v${{ env.VERSION }}'

      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          # docker-image: testing
          extra-build-deps: lsb-release
          before-build-hook: |
            echo "::group::lsb_release -a"
            lsb_release -a
            echo "::endgroup::"
            echo "::group::uname -a"
            uname -a
            echo "::endgroup::"
          buildpackage-opts: --build=binary --no-sign

      - name: Get infos/contents for package
        run: |
          echo "::group::Get infos"
          dpkg --info debian/artifacts/pop-icon-theme_${{ env.VERSION }}_all.deb
          echo "::endgroup::"
          echo "::group::Get contents"
          dpkg --contents debian/artifacts/pop-icon-theme_${{ env.VERSION }}_all.deb
          echo "::endgroup::"

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          path: debian/artifacts/pop-icon-theme_${{ env.VERSION }}_all.deb
          if-no-files-found: error
          retention-days: 1
          archive: false
