name: Publish COSMIC release

on:
  push:
    tags:
      - "*.*.*"

env:
  VERSION: ${{ github.ref_name }}

permissions: {}

# Prevents concurrent runs of the workflow
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  valid-version:
    name: Validate tag for version
    runs-on: ubuntu-latest
    steps:
      - name: Validate version
        run: |
          if [[ "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Valid version: ${VERSION}"
          else
            echo "Invalid tag for version: ${VERSION}"
            exit 1
          fi

  build:
    name: Build ${{ matrix.component }}
    needs: valid-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - cosmic-applets
          - cosmic-app-library
          - cosmic-bg
          - cosmic-comp
          - cosmic-icons
          - cosmic-idle
          - cosmic-launcher
          - cosmic-notifications
          - cosmic-osd
          - cosmic-panel
          - cosmic-randr
          - cosmic-screenshot
          - cosmic-session
          - cosmic-settings
          - cosmic-settings-daemon
          - cosmic-workspaces
          - pop-launcher
          - xdg-desktop-portal-cosmic
        arch:
          - amd64
        lfs:
          - false
        include:
          # Special case to use LFS for these components
          - {component: cosmic-greeter, arch: amd64, lfs: true }
          - {component: cosmic-initial-setup, arch: amd64, lfs: true }
          # arch != amd64
          - {component: cosmic-wallpapers, arch: all, lfs: true}

    steps:
      - name: Checkout sources
        if: ${{ matrix.component != 'cosmic-workspaces' && matrix.component != 'pop-launcher' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: pop-os/${{ matrix.component }}
          ref: epoch-${{ env.VERSION }}
          lfs: ${{ matrix.lfs }}
          persist-credentials: false

      # Special case for cosmic-workspaces repository (repo = pop-os/cosmic-workspaces-epoch)
      - name: Checkout sources for cosmic-workspaces
        if: ${{ matrix.component == 'cosmic-workspaces' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: pop-os/cosmic-workspaces-epoch
          ref: epoch-${{ env.VERSION }}
          persist-credentials: false

      # Special case for pop-launcher repository (repo = pop-os/launcher)
      - name: Checkout sources for pop-launcher
        if: ${{ matrix.component == 'pop-launcher' }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: pop-os/launcher
          ref: epoch-${{ env.VERSION }}
          persist-credentials: false

      - name: Checkout changelog for ${{ matrix.component }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          path: local-debian
          sparse-checkout: |
            changelog/${{ matrix.component }}
          sparse-checkout-cone-mode: false
          persist-credentials: false

      - name: Check changelog for ${{ matrix.component }}
        run: |
          filename="local-debian/changelog/${{ matrix.component }}"
          if [ -r "$filename" ]; then
            cp -v "$filename" debian/changelog
            echo "### changelog file"
            cat debian/changelog
          else
            echo "ERROR: no changelog file for ${{ matrix.component }}"
            exit 1
          fi

      - name: Build package
        uses: jtdor/build-deb-action@473136f14a42a231124c1f7cefaedfe941203c38  #v1.9.1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          extra-build-deps: devscripts dpkg-dev libdistro-info-perl  # needed for dch and dpkg-parsechangelog tools
          setup-hook: |
            # Special case for cosmic-osd => rewrite debian/control file to remove
            # unecessary Build-Depends on cosmic-randr
            if grep -q "cosmic-osd" Cargo.toml; then
              sed -i '/cosmic-randr,/d' debian/control
            fi
            # Special case for cosmic-session => rewrite debian/control file to remove
            # unecessary Build-Depends on cosmic-files
            if grep -q -E "Source: cosmic-session$" debian/control; then
              sed -i '/cosmic-files,/d' debian/control
            fi
            # Special case for cosmic-settings => rewrite debian/control file
            # to replace network-manager-gnome by network-manager-applet
            if grep -q -E "Source: cosmic-settings$" debian/control; then
              sed -i 's/network-manager-gnome/network-manager-applet/' debian/control
            fi
          before-build-hook: |
            # Special case for cosmic-initial-setup, cosmic-osd, cosmic-settings
            # and cosmic-session => rewrite debian/rules file to remove vendor
            if grep "name" Cargo.toml | grep -q -E "cosmic-initial-setup|cosmic-osd|cosmic-session"; then
              sed -i '/override_dh_auto_clean/,+2d' debian/rules
            fi
            if [ "${{ matrix.component }}" = "cosmic-settings" ]; then
              sed -i '/override_dh_auto_clean/,+2d' debian/rules
            fi
            # Replace build target in debian/rules files + no vendoring
            sed -i 's/VENDOR ?= 1/VENDOR ?= 0/' debian/rules
            sed -i 's/build-vendored/build-release/' debian/rules

            printf '### debian/rules file\n%s\n' "$(cat debian/rules)"

            echo "::group::Update changelog"
            current_version=$(dpkg-parsechangelog --show-field Version)
            printf "current_version = %s\n" "${current_version}"
            # Check version env.version > current version with 'sort -V'
            if [ "${current_version}" != "${{ env.VERSION }}" ] && [ "$(printf '%s\n%s\n' "${current_version}" "${{ env.VERSION }}" | sort -V | head -n1)" = "${current_version}" ]; then
              echo "new version = ${{ env.VERSION }}"
              DEBEMAIL=foxy@free.fr DEBFULLNAME="Laurent Cheylus" dch -v "${{ env.VERSION }}"  --distribution testing "new version for upstream release COSMIC epoch-${{ env.VERSION }}"
            else
              echo "No need to update changelog for version ${{ env.VERSION }}"
            fi
            cp -v debian/changelog "local-debian/changelog/${{ matrix.component }}"
            # Dump content without trailing newlines
            printf '### debian/changelog file\n%s' "$(cat debian/changelog)"
            echo "::endgroup::"

          buildpackage-opts: --build=binary --no-sign

      - name: Get infos/contents for package
        run: |
          if [ "${{ matrix.component }}" == "cosmic-greeter" ]; then
            echo "::group::Get infos for ${{ matrix.component }} package"
            dpkg --info debian/artifacts/${{ matrix.component }}_"${VERSION}"_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }} package"
            dpkg --contents debian/artifacts/${{ matrix.component }}_"${VERSION}"_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get infos for ${{ matrix.component }}-daemon package"
            dpkg --info debian/artifacts/${{ matrix.component }}-daemon_"${VERSION}"_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }}-daemon package"
            dpkg --contents debian/artifacts/${{ matrix.component }}-daemon_"${VERSION}"_${{ matrix.arch }}.deb
            echo "::endgroup::"
          else
            echo "::group::Get infos for ${{ matrix.component }} package"
            dpkg --info debian/artifacts/${{ matrix.component }}_"${VERSION}"_${{ matrix.arch }}.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.component }} package"
            dpkg --contents debian/artifacts/${{ matrix.component }}_"${VERSION}"_${{ matrix.arch }}.deb
            echo "::endgroup::"
          fi

      # TODO: add case to upload pop-launcher-system76-power package (pop-launcher)
      - name: Upload package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.component }}_${{ env.VERSION }}_${{ matrix.arch }}.deb
          if-no-files-found: error
          retention-days: 1
          archive: false

      # Special case for cosmic-greeter component: 2 packages built
      - name: Upload cosmic-greeter-daemon
        if: ${{ matrix.component == 'cosmic-greeter' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.component }}-daemon_${{ env.VERSION }}_${{ matrix.arch }}.deb
          if-no-files-found: error
          retention-days: 1
          archive: false

      - name: Upload changelog file for ${{ matrix.component }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          name: ${{ matrix.component }}
          path: "local-debian/changelog/${{ matrix.component }}"
          if-no-files-found: error
          retention-days: 1

  build-apps:
    name: Build ${{ matrix.app }}
    needs: valid-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [cosmic-edit, cosmic-files, cosmic-monitor, cosmic-player, cosmic-store, cosmic-term]

    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: pop-os/${{ matrix.app }}
          ref: epoch-${{ env.VERSION }}
          persist-credentials: false

      - name: Build package
        uses: jtdor/build-deb-action@473136f14a42a231124c1f7cefaedfe941203c38  #v1.9.1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: debian:testing
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: ca-certificates
          before-build-hook: |
            # Replace build target in debian/rules files + no vendoring
            sed -i 's/VENDOR ?= 1/VENDOR ?= 0/' debian/rules
            sed -i 's/build-vendored/build-release/' debian/rules
            echo "### debian/rules file"
            cat debian/rules

            # Remove .cargo/config.toml with vendored sources
            if [ -f .cargo/config.toml ]; then rm .cargo/config.toml; fi

      - name: Get infos/contents for package
        run: |
          echo "::group::Get infos for ${{ matrix.app }} package"
          dpkg --info debian/artifacts/${{ matrix.app }}_"${VERSION}"_amd64.deb
          echo "::endgroup::"
          echo "::group::Get contents for ${{ matrix.app }} package"
          dpkg --contents debian/artifacts/${{ matrix.app }}_"${VERSION}"_amd64.deb
          echo "::endgroup::"

      - name: Upload package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.app }}_${{ env.VERSION }}_amd64.deb
          if-no-files-found: error
          retention-days: 1
          archive: false

  release:
    name: Create release for COSMIC
    needs: [build, build-apps]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create a release

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  #v8.0.1
        with:
          pattern: "*.deb"
          merge-multiple: true
          skip-decompress: true

      - name: Check downloaded artifacts
        run: |
          ls -l *.deb
          count=$(find . -maxdepth 1 -type f -name '*.deb' | wc -l)
          # 22 artifacts for components + 6 apps
          if [ "$count" -ne  28 ]; then
            echo "ERROR: Expected 28 .deb files, found $count"
            exit 1
          fi

      - name: Generate SHA256SUMS file
        run: find . -maxdepth 1 -type f -name '*.deb' -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS

      - name: Publish release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228  #v3.0.2
        with:
          files: |
            SHA256SUMS
            *.deb
          fail_on_unmatched_files: true
          make_latest: true
          name: "Release for COSMIC Epoch ${{ env.VERSION }}"
          body: >
            Debian testing packages to install COSMIC Desktop Environment
            [version epoch-${{ env.VERSION }}](https://github.com/pop-os/cosmic-epoch/releases/tag/epoch-${{ env.VERSION }})


            Contains all the components necessary to install COSMIC DE and optional applications
            (Edit, Files, Monitor, Player, Store and Term).

  commit-changelog:
    name: Commit updated changelog
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow to commit file
    steps:
      - name: Checkout changelog files
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          sparse-checkout: |
            changelog

      # All artifacts are downloaded, also unwanted *.deb files
      - name: Download changelog files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  #v8.0.1
        with:
          path: changelog
          merge-multiple: true

      - name: Check changelog files
        run: |
          rm -f changelog/*.deb
          ls -l changelog
          echo "### git status"
          git status

      - name: Commit changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "changelog"
          git commit -m "Update changelog for COSMIC components after release version ${VERSION}"
          # Need to push on main branch, repo is in detached state for current tag
          git push origin HEAD:main

  create-badge:
    name: Update dynamic badge
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: schneegans/dynamic-badges-action@28b0fa8bdeb46170ac397105ece0c1fe58f68910  #v1.9.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6709cbe37e469a749fd3e179dd03c0db
          filename: cosmic-badge.json
          forceUpdate: true
          label: COSMIC version
          message: Epoch ${{ env.VERSION }}
          color: blue
