name: Create release for COSMIC depends
on: workflow_dispatch

permissions: {}

# Prevents concurrent runs of the workflow
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {name: adw-gtk3, repo: adw-gtk3, version: 5.3.0-0pop1 }
          - {name: appstream-data-pop, repo: appstream-data, version: 0.0.3 }
          - {name: pop-icon-theme, repo: icon-theme, version: 3.5.1 }
          - {name: pop-fonts, repo: fonts, version: 1.0.3 }
          - {name: pop-sound-theme, repo: gtk-theme, version: 5.5.1 }

    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          repository: 'pop-os/${{ matrix.repo }}'
          persist-credentials: false

      - name: Build package
        uses: jtdor/build-deb-action@473136f14a42a231124c1f7cefaedfe941203c38  #v1.9.1
        with:
          docker-image: debian:testing
          buildpackage-opts: --build=binary --no-sign

      - name: Get infos/contents for packages
        run: |
          if [ "${{ matrix.name }}" == "appstream-data-pop" ]; then
            echo "::group::Get infos for ${{ matrix.name }} package"
            dpkg --info debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_all.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.name }} package"
            dpkg --contents debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_all.deb
            echo "::endgroup::"
            echo "::group::Get infos for ${{ matrix.name }}-icons package"
            dpkg --info debian/artifacts/${{ matrix.name }}-icons_${{ matrix.version }}_all.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.name }}-icons package"
            dpkg --contents debian/artifacts/${{ matrix.name }}-icons_${{ matrix.version }}_all.deb
            echo "::endgroup::"
            echo "::group::Get infos for ${{ matrix.name }}-icons-hidpi package"
            dpkg --info debian/artifacts/${{ matrix.name }}-icons-hidpi_${{ matrix.version }}_all.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.name }}-icons-hidpi package"
            dpkg --contents debian/artifacts/${{ matrix.name }}-icons-hidpi_${{ matrix.version }}_all.deb
            echo "::endgroup::"
          else
            echo "::group::Get infos for ${{ matrix.name }} package"
            dpkg --info debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_all.deb
            echo "::endgroup::"
            echo "::group::Get contents for ${{ matrix.name }} package"
            dpkg --contents debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_all.deb
            echo "::endgroup::"
          fi

      - name: Upload package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.name }}_${{ matrix.version }}_all.deb
          if-no-files-found: error
          retention-days: 7
          archive: false

      # Multiple packages for appstream-data-pop
      - name: Upload appstream-data-pop-icons
        if: ${{ matrix.name == 'appstream-data-pop' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.name }}-icons_${{ matrix.version }}_all.deb
          if-no-files-found: error
          retention-days: 7
          archive: false
      - name: Upload appstream-data-pop-icons-hidpi
        if: ${{ matrix.name == 'appstream-data-pop' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  #v7.0.1
        with:
          path: debian/artifacts/${{ matrix.name }}-icons-hidpi_${{ matrix.version }}_all.deb
          if-no-files-found: error
          retention-days: 7
          archive: false

  release:
    name: Create release for COSMIC depends
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create a release

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  #v8.0.1
        with:
          pattern: "*.deb"
          merge-multiple: true
          skip-decompress: true

      - name: Check downloaded artifacts
        run: |
          ls -l *.deb
          count=$(find . -maxdepth 1 -type f -name '*.deb' | wc -l)
          if [ "$count" -ne 7 ]; then
            echo "ERROR: Expected 7 .deb files, found $count"
            exit 1
          fi

      - name: Generate SHA256SUMS file
        run: find . -maxdepth 1 -type f -name '*.deb' -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS

      - name: Get version for packages
        id: version
        run: |
          echo "adw-gtk3=$(find . -type f -name 'adw-gtk3*.deb' | cut -d"_" -f2)" >> "$GITHUB_OUTPUT"
          echo "appstream-data=$(find . -type f -name 'appstream-data-pop_*.deb' | cut -d"_" -f2)" >> "$GITHUB_OUTPUT"
          echo "pop-fonts=$(find . -type f -name 'pop-fonts*.deb' | cut -d"_" -f2)" >> "$GITHUB_OUTPUT"
          echo "pop-icon=$(find . -type f -name 'pop-icon*.deb' | cut -d"_" -f2)" >> "$GITHUB_OUTPUT"
          echo "pop-sound=$(find . -type f -name 'pop-sound*.deb' | cut -d"_" -f2)" >> "$GITHUB_OUTPUT"

          echo "Contents of GITHUB_OUTPUT:"
          cat "$GITHUB_OUTPUT"

      - name: Set current date
        id: date
        run: echo "value=$(date +%F)" >> "$GITHUB_OUTPUT"

      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64  # v3.0.3
        with:
          draft: true
          files: |
            SHA256SUMS
            *.deb
          fail_on_unmatched_files: true
          make_latest: false
          name: "COSMIC depends - ${{ steps.date.outputs.value }}"
          body: |
            Debian packages needed by COSMIC components and apps, not available in official Debian testing packages.

            - [adw-gtk3](https://github.com/pop-os/adw-gtk3): unofficial GTK3 port of libadwaita (version ${{ steps.version.outputs.adw-gtk3 }})
            - [appstream-data-pop*](https://github.com/pop-os/appstream-data): additional appstream data for Pop!_OS (version ${{ steps.version.outputs.appstream-data }})
            - [pop-fonts](https://github.com/pop-os/fonts): fonts for System76/COSMIC (version ${{ steps.version.outputs.pop-fonts }})
            - [pop-icon-theme](https://github.com/pop-os/icon-theme): standard icons for Pop!_OS (version ${{ steps.version.outputs.pop-icon }})
            - [pop-sound-theme](https://github.com/pop-os/gtk-theme/): sound themes for Pop!_OS (version ${{ steps.version.outputs.pop-sound }})

      - name: Generate summary
        run: |
          echo "## Results for release of COSMIC depends" >> $GITHUB_STEP_SUMMARY
          echo "Release published as draft - needs to publish it with tag = depends-$(date +%F | sed 's/-//g')" >> $GITHUB_STEP_SUMMARY
          echo "URL for release = ${{ steps.publish.outputs.url }}" >> $GITHUB_STEP_SUMMARY
