# GH workflow to update Debian APT repository with deb files from
# COSMIC latest release and COSMIC depends
name: Update COSMIC APT Repository

on: workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Prevents concurrent runs of the workflow
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  upload-artifacts:
    name: Upload artifacts for APT repo
    runs-on: ubuntu-latest
    env:
      DEPENDS_TAG: depends-20260808  # Tag for release of COSMIC Depends
      GH_TOKEN: ${{ github.token }}

    steps:
      # Step mandatory to use 'gh release' command
      - name: Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          persist-credentials: false

      - name: Download artifacts from latest release
        run: |
          mkdir -p packages
          gh release download --pattern '*.deb' --dir packages

      - name: Check downloaded artifacts from latest release
        run: |
          ls -l packages/*.deb
          count=$(find packages -maxdepth 1 -type f -name '*.deb' | wc -l)
          # 22 artifacts for components + 6 apps
          if [ "$count" -ne  28 ]; then
            echo "ERROR: Expected 28 .deb files, found $count"
            exit 1
          fi

      - name: Download artifacts from depends release
        run: |
          mkdir -p depends
          gh release download ${DEPENDS_TAG} --pattern '*.deb' --dir depends

      - name: Check downloaded artifacts from depends release
        run: |
          ls -l depends/*.deb
          count=$(find depends -maxdepth 1 -type f -name '*.deb' | wc -l)
          if [ "$count" -ne  7 ]; then
            echo "ERROR: Expected 7 .deb files, found $count"
            exit 1
          fi

      - name: Create directory for artifacts
        run: |
          mkdir -p artifacts
          cp -va packages/*.deb artifacts
          cp -va depends/*.deb artifacts

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d  # v6.0.0

      - name: Create APT Repository
        id: create-apt-repo
        uses: morph027/apt-repo-action@016866b2950ae9d3d0245686bac6befe3788886e  #v3.7
        with:
          repo-name: cosmic-debian
          scan-dir: artifacts
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-key-passphrase: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          codename: forky
          suite: testing
          components: main
          architectures: amd64
          origin: Debian APT Repository for COSMIC DE - https://github.com/lcheylus/cosmic-debian/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  #v5.0.0
        with:
          name: github-pages
          path: ${{ steps.create-apt-repo.outputs.dir }}
