# GH workflow to update Debian APT repository with deb files from
# COSMIC latest release and COSMIC depends
name: Update COSMIC APT Repository

on: workflow_dispatch

env:
  REPO_NAME: cosmic-debian
  CODENAME: forky
  COMPONENTS: main

permissions: {}

# Prevents concurrent runs of the workflow
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  upload-artifacts:
    name: Upload artifacts for APT repo
    runs-on: ubuntu-latest
    env:
      DEPENDS_TAG: depends-20260808  # Tag for release of COSMIC Depends
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: read
    outputs:
      keyring: ${{ steps.create-apt-repo.outputs.keyring }}

    steps:
      # Step mandatory to use 'gh release' command
      - name: Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          persist-credentials: false

      - name: Download artifacts from latest release
        run: |
          mkdir -p packages
          gh release download --pattern '*.deb' --dir packages

      - name: Check downloaded artifacts from latest release
        run: |
          ls -l packages/*.deb
          count=$(find packages -maxdepth 1 -type f -name '*.deb' | wc -l)
          # 22 artifacts for components + 6 apps
          if [ "$count" -ne  28 ]; then
            echo "ERROR: Expected 28 .deb files, found $count"
            exit 1
          fi

      - name: Download artifacts from depends release
        run: |
          mkdir -p depends
          gh release download ${DEPENDS_TAG} --pattern '*.deb' --dir depends

      - name: Check downloaded artifacts from depends release
        run: |
          ls -l depends/*.deb
          count=$(find depends -maxdepth 1 -type f -name '*.deb' | wc -l)
          if [ "$count" -ne  7 ]; then
            echo "ERROR: Expected 7 .deb files, found $count"
            exit 1
          fi

      - name: Create directory for artifacts
        run: |
          mkdir -p artifacts
          cp -va packages/*.deb artifacts
          cp -va depends/*.deb artifacts

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d  # v6.0.0

      - name: Create APT Repository
        id: create-apt-repo
        uses: morph027/apt-repo-action@b6b977523e6a5e235075787489bb073c60b71eb4  # v3.8
        with:
          repo-name: ${{ env.REPO_NAME }}
          scan-dir: artifacts
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-key-passphrase: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          codename: ${{ env.CODENAME }}
          suite: testing
          components: ${{ env.COMPONENTS }}
          architectures: amd64
          origin: Debian APT Repository for COSMIC DE - https://github.com/lcheylus/cosmic-debian/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  #v5.0.0
        with:
          name: github-pages
          path: ${{ steps.create-apt-repo.outputs.dir }}

  # Job to deploy APT Repository on GitHub pages
  deploy:
    name: Deploy to GitHub Pages
    needs: upload-artifacts
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write  # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346  # v5.0.1

      - name: Adding summary
        run: |
          echo '### Commands to install COSMIC Debian APT Repository' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo 'sudo curl -sfLo /etc/apt/keyrings/${{ needs.upload-artifacts.outputs.keyring }}.asc ${{ steps.deployment.outputs.page_url }}gpg.key' >> $GITHUB_STEP_SUMMARY
          echo 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/${{ needs.upload-artifacts.outputs.keyring }}.asc] ${{ steps.deployment.outputs.page_url }} ${{ env.CODENAME }} ${{ env.COMPONENTS }}" | sudo tee /etc/apt/sources.list.d/${{ env.REPO_NAME }}.list' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
